theme: jekyll-theme-slate

title: "COMP 290-01"
description: "Large-scale and Open Source Software Development - Dickinson College"

hide_first_title: true
show_downloads: false
buttons:
  zip_hide: true
  tar_hide: true
  github_hide: true
